# Generated by Django 3.1.1 on 2020-09-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_identification_number', models.CharField(max_length=10)),
                ('PRD_function', models.CharField(max_length=150)),
                ('installation_date_of_PRD', models.DateTimeField(auto_now=True)),
                ('RBI_assessment_data', models.DateTimeField(auto_now=True)),
                ('Type_of_PRD', models.CharField(choices=[('IPRD- 1', 'IPRD- 1'), ('IPRD- 2', 'IPRD- 2'), ('IPRD- 3', 'IPRD- 3'), ('IPRD- 4', 'IPRD- 4'), ('IPRD- 5', 'IPRD- 5'), ('IPRD- 6', 'IPRD- 6'), ('IPRD- 7', 'IPRD- 7'), ('IPRD- 8', 'IPRD- 8'), ('IPRD- 9', 'IPRD- 9'), ('IPRD- 10', 'IPRD- 10'), ('IPRD- 11', 'IPRD- 11'), ('IPRD- 12', 'IPRD- 12'), ('IPRD- 13', 'IPRD- 13'), ('IPRD- 14', 'IPRD- 14'), ('IPRD- 15', 'IPRD- 15'), ('IPRD- 16', 'IPRD- 16'), ('IPRD- 17', 'IPRD- 17'), ('IPRD- 18', 'IPRD- 18'), ('IPRD- 19', 'IPRD- 19'), ('IPRD- 20', 'IPRD- 20'), ('IPRD- 21', 'IPRD- 21'), ('IPRD- 22', 'IPRD- 22'), ('IPRD- 23', 'IPRD- 23'), ('IPRD- 24', 'IPRD- 24'), ('IPRD- 25', 'IPRD- 25'), ('IPRD- 26', 'IPRD- 26'), ('IPRD- 27', 'IPRD- 27'), ('IPRD- 28', 'IPRD- 28'), ('IPRD- 29', 'IPRD- 29'), ('IPRD- 30', 'IPRD- 30'), ('IPRD- 31', 'IPRD- 31'), ('IPRD- 32', 'IPRD- 32'), ('IPRD- 33', 'IPRD- 33')], default='Choose...', max_length=10)),
            ],
            options={
                'ordering': ['PRD_identification_number'],
            },
        ),
    ]
