# Generated by Django 3.1.1 on 2020-09-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prd',
            name='RBI_assessment_data',
        ),
        migrations.RemoveField(
            model_name='prd',
            name='installation_date_of_PRD',
        ),
        migrations.AlterField(
            model_name='prd',
            name='Type_of_PRD',
            field=models.CharField(choices=[('IPRD_3_first', 'Convention Spring-Loaded'), ('IPRD_3_second', 'Balanced Bellows'), ('IPRD_3_third', 'Pilot Operated'), ('IPRD_3_fourth', 'PRV with Rupture Disk'), ('IPRD_3_fifth', 'Rupture Disk Only')], default='Choose...', max_length=25),
        ),
    ]
