# Generated by Django 3.1.4 on 2021-01-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210125_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrdInspection_TestHistory',
            new_name='ProtectedFixedEquipmentPipingData',
        ),
    ]
