# Generated by Django 3.1.4 on 2021-01-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210112_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prdinspection_testhistory',
            options={'ordering': ['id']},
        ),
    ]
