# Generated by Django 3.1.4 on 2021-01-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210112_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consequences0ffailureofleakage',
            options={'ordering': ['id']},
        ),
    ]
