# Generated by Django 3.1.1 on 2020-09-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200922_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd',
            name='PRD_Containing_Soft_Seats',
            field=models.CharField(choices=[('IPRD_4_first', 'No'), ('IPRD_4_second', 'Yes')], default='IPRD_4_first', max_length=15),
        ),
    ]
