# Generated by Django 3.1.4 on 2021-01-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210125_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Inspection_Effectiveness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.prdinspectioneffectiveness'),
        ),
    ]
