# Generated by Django 3.1.4 on 2021-01-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210112_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicableoverpressuredemandcase',
            options={'ordering': ['id']},
        ),
    ]
