# Generated by Django 3.1.1 on 2020-09-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_prd_prd_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd',
            name='Service_severity',
            field=models.CharField(choices=[('IPRD_6_first', 'Mild'), ('IPRD_6_second', 'Moderate'), ('IPRD_6_third', 'Severe'), ('IPRD_6_fourth', 'PRV with Rupture Disk'), ('IPRD_6_fifth', 'Rupture Disk Only')], default='IPRD_6_first', max_length=15),
        ),
    ]
