# Generated by Django 3.1.4 on 2021-01-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210112_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectfield',
            name='OverPressureDemandCase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.overpressuredemandcase'),
        ),
        migrations.AddField(
            model_name='selectfield',
            name='PRDInspectionEffectiveness',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.prdinspectioneffectiveness'),
        ),
        migrations.AddField(
            model_name='selectfield',
            name='ProtectedEquipmentDemageStatus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.protectedequipmentdemagestatus'),
        ),
    ]
