# Generated by Django 3.1.1 on 2020-09-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_prd_service_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd',
            name='Service_severity',
            field=models.CharField(choices=[('IPRD_6_first', 'Mild'), ('IPRD_6_second', 'Moderate'), ('IPRD_6_third', 'Severe')], default='IPRD_6_first', max_length=15),
        ),
    ]
