# Generated by Django 3.1.4 on 2021-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210130_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='PRD_leakage_can_be_tolered',
            field=models.CharField(choices=[('No', 'No'), ('yes', 'Yes')], default='no', max_length=14),
        ),
        migrations.AlterField(
            model_name='consequencesoffailureinputdata',
            name='Multiple_PRDs_protecting_fixed_equipment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='yes', max_length=14),
        ),
        migrations.AlterField(
            model_name='environmentfactormodifier',
            name='name',
            field=models.CharField(choices=[('Operating temperatures 99.33 °C < T < 260 °C', 'Operating temperatures 99.33 °C < T < 260 °C'), ('Operating temperature > 260 °C', 'Operating temperature > 260 °C'), ('Operating ratio > 90%\\ for spring-loaded PRVs or > 95% for pilot operated', 'Operating ratio > 90%\\ for spring-loaded PRVs or > 95% for pilot operated'), ('Installed piping vibration', 'Installed piping vibration'), ('Pulsating or cyclical service such as downstream of positive displacement rotating equipment', 'Pulsating or cyclical service such as downstream of positive displacement rotating equipment'), ('History of excessive actuation in service (greater than 5 times per year', 'History of excessive actuation in service (greater than 5 times per year'), ('History of chatter', 'History of chatter')], default='99.33 °C < T < 260 °C', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='PRD_Containing_Soft_Seats',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=15),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='Rupture_disk_is_installed_upstream_of_PRD',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=13),
        ),
        migrations.AlterField(
            model_name='overpressuredemandcase',
            name='name',
            field=models.CharField(choices=[('1. Fire', '1. Fire'), ('2. Loss of cooling water utility', '2. Loss of cooling water utility'), ('electrical_power_supply_failure', '3. Electrical power supply failure'), ('4. Blockage discharge with administrative controls in place', '4. Blockage discharge with administrative controls in place'), ('5. Blockage discharge without administrative controls', '5. Blockage discharge without administrative controls'), ('6. Control valve failure, initiating event is same direction as CV normal fail position (i.e. fail safe)', '6. Control valve failure, initiating event is same direction as CV normal fail position (i.e. fail safe)'), ('7. Control valve failure, initiating event is opposite direction as CV normal fail posiion (i.e. fail opposite)', '7. Control valve failure, initiating event is opposite direction as CV normal fail posiion (i.e. fail opposite)'), ('8. Runaway chemical reaction', '8. Runaway chemical reaction'), ('9. Heat exchanger tube rupture', '9. Heat exchanger tube rupture'), ('10. Tower P/A or reflux pump failures', '10. Tower P/A or reflux pump failures'), ('11. Thermal relief with administrative controls in place', '11. Thermal relief with administrative controls in place'), ('12. Thermal relief without administrative controls', '12. Thermal relief without administrative controls'), ('13. Liquid overfilling with administrative controls in place', '13. Liquid overfilling with administrative controls in place'), ('14. Liquid overfilling without administrative controls', '14. Liquid overfilling without administrative controls')], default='fire', max_length=200),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Leakage_results',
            field=models.CharField(choices=[('None', 'None'), ('Leak', 'Leak'), ('No Leak', 'No Leak')], default='pass', max_length=15),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Overhauled_during_the_inspection',
            field=models.CharField(choices=[('None', 'None'), ('Yes', 'Yes'), ('No', 'No')], default='yes', max_length=14),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_pop_test_results',
            field=models.CharField(choices=[('None', 'None'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='fire', max_length=15),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_replace_with_new_PRD_in_lieu_of_overhaul',
            field=models.CharField(choices=[('None', 'None'), ('Yes', 'Yes'), ('No', 'No')], default='no', max_length=14),
        ),
        migrations.AlterField(
            model_name='prddischargelocation',
            name='name',
            field=models.CharField(choices=[('Atmosphere', 'Atmosphere'), ('Flare', 'Flare'), ('Closed Process', 'Closed Process')], default='atmosphere', max_length=25),
        ),
        migrations.AlterField(
            model_name='prdinspectioneffectiveness',
            name='name',
            field=models.CharField(choices=[('None', 'None'), ('Highly Effective', 'Highly Effective'), ('Usually Effective', 'Usually Effective'), ('Faily Effective', 'Faily Effective')], default='highly_effective', max_length=30),
        ),
        migrations.AlterField(
            model_name='protectedequipmentdemagestatus',
            name='name',
            field=models.CharField(choices=[('None', 'None'), ('Minimal', 'Minimal'), ('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='protectedfixedequipmentpipingdata',
            name='Fixed_Equipment_Protected_by_PRD',
            field=models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceseverity',
            name='name',
            field=models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='mild', max_length=15),
        ),
        migrations.AlterField(
            model_name='typeofprd',
            name='name',
            field=models.CharField(choices=[('Convention Spring-Loaded', 'Convention Spring-Loaded'), ('Balanced Bellows', 'Balanced Bellows'), ('Pilot Operated', 'Pilot Operated'), ('Rupture Disk Only', 'Rupture Disk Only')], default='convention_spring_loaded', max_length=30),
        ),
    ]
