# Generated by Django 3.1.4 on 2021-03-07 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210213_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consequences0fFailureOfLeakage',
            new_name='ConsequencesOfFailureOfLeakage',
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='Installation_of_PRD',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='RBI_assessment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
