# Generated by Django 3.1.1 on 2020-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200922_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd',
            name='PRD_Discharge_Location',
            field=models.CharField(choices=[('IPRD_7_first', 'Atmosphere'), ('IPRD_7_second', 'Flare'), ('IPRD_7_third', 'Closed Process')], default='IPRD_7_first', max_length=25),
        ),
    ]
