# Generated by Django 3.1.4 on 2021-01-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_applicableoverpressuredemandcase_consequences0ffailureofleakage_consequencesoffailureinputdata_envir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicableOverpressureDemandCase',
        ),
        migrations.DeleteModel(
            name='Consequences0fFailureOfLeakage',
        ),
    ]
