# Generated by Django 3.1.1 on 2020-09-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_prd_environment_factor_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd',
            name='Environment_Factor_Modifier',
            field=models.CharField(choices=[('IPRD_8_first', 'Operating temperatures 99.33 °C < T < 260 °C'), ('IPRD_8_second', 'Moderate'), ('IPRD_8_third', 'Severe')], default='IPRD_8_first', max_length=30),
        ),
    ]
