# Generated by Django 3.1.4 on 2021-03-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_allmodels_projectregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectregistration',
            name='project',
        ),
        migrations.DeleteModel(
            name='AllModels',
        ),
        migrations.DeleteModel(
            name='ProjectRegistration',
        ),
    ]
