# Generated by Django 3.1.4 on 2021-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_applicableoverpressuredemandcase_consequences0ffailureofleakage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentfactormodifier',
            name='Environment_Factor_Modifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='overpressuredemandcase',
            name='Over_pressure_demand_case',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prddischargelocation',
            name='PRD_Discharge_Location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='prdinspectioneffectiveness',
            name='PRD_Inspection_Effectiveness',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='protectedequipmentdemagestatus',
            name='Protected_Equipment_Demage_Status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceseverity',
            name='Service_severity',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='typeofprd',
            name='Type_of_PRD',
            field=models.CharField(max_length=30),
        ),
    ]
