# Generated by Django 3.1.1 on 2020-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200922_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd',
            name='Rupture_disk_is_installed_upstream_of_PRD',
            field=models.CharField(choices=[('IPRD_9_first', 'No'), ('IPRD_9_second', 'Yes')], default='IPRD_9_first', max_length=13),
        ),
        migrations.AlterField(
            model_name='prd',
            name='Environment_Factor_Modifier',
            field=models.CharField(choices=[('IPRD_8_first', 'Operating temperatures 99.33 °C < T < 260 °C'), ('IPRD_8_second', 'Operating temperature > 260 °C'), ('IPRD_8_third', 'Operating ratio > 90% for spring-loaded PRVs or > 95% for pilot operated'), ('IPRD_8_fourth', 'Installed piping vibration'), ('IPRD_8_fifth', 'Pulsating or cyclical service such as downstream of positive displacement rotating equipment'), ('IPRD_8_sixth', 'History of excessive actuation in service (greater than 5 times per year'), ('IPRD_8_seventh', 'History of chatter')], default='IPRD_8_first', max_length=30),
        ),
    ]
