# Generated by Django 3.1.4 on 2021-03-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210307_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_Inspection_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.prd_inspectionhistory')),
                ('applicable_overpressure_demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.applicableoverpressuredemandcase')),
                ('consequence_of_failure_input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.consequencesoffailureinputdata')),
                ('consequence_of_failure_leakage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.consequencesoffailureofleakage')),
                ('general_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.generalinformation')),
                ('protected_fixed_equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.protectedfixedequipmentpipingdata')),
            ],
            options={
                'verbose_name_plural': 'All Models',
            },
        ),
    ]
