# Generated by Django 3.1.1 on 2020-09-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200922_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_identification_number', models.CharField(max_length=10)),
                ('PRD_function', models.CharField(max_length=150)),
                ('Type_of_PRD', models.CharField(choices=[('IPRD_3_first', 'Convention Spring-Loaded'), ('IPRD_3_second', 'Balanced Bellows'), ('IPRD_3_third', 'Pilot Operated'), ('IPRD_3_fourth', 'PRV with Rupture Disk'), ('IPRD_3_fifth', 'Rupture Disk Only')], default='IPRD_3_first', max_length=25)),
                ('PRD_Containing_Soft_Seats', models.CharField(choices=[('IPRD_4_first', 'No'), ('IPRD_4_second', 'Yes')], default='IPRD_4_first', max_length=15)),
                ('PRD_set', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('Service_severity', models.CharField(choices=[('IPRD_6_first', 'Mild'), ('IPRD_6_second', 'Moderate'), ('IPRD_6_third', 'Severe')], default='IPRD_6_first', max_length=15)),
                ('PRD_Discharge_Location', models.CharField(choices=[('IPRD_7_first', 'Atmosphere'), ('IPRD_7_second', 'Flare'), ('IPRD_7_third', 'Closed Process')], default='IPRD_7_first', max_length=25)),
                ('Environment_Factor_Modifier', models.CharField(choices=[('IPRD_8_first', 'Operating temperatures 99.33 °C < T < 260 °C'), ('IPRD_8_second', 'Operating temperature > 260 °C'), ('IPRD_8_third', 'Operating ratio > 90% for spring-loaded PRVs or > 95% for pilot operated'), ('IPRD_8_fourth', 'Installed piping vibration'), ('IPRD_8_fifth', 'Pulsating or cyclical service such as downstream of positive displacement rotating equipment'), ('IPRD_8_sixth', 'History of excessive actuation in service (greater than 5 times per year'), ('IPRD_8_seventh', 'History of chatter')], default='IPRD_8_first', max_length=30)),
                ('Rupture_disk_is_installed_upstream_of_PRD', models.CharField(choices=[('IPRD_9_first', 'No'), ('IPRD_9_second', 'Yes')], default='IPRD_9_first', max_length=13)),
            ],
            options={
                'ordering': ['PRD_identification_number'],
            },
        ),
    ]
