# Generated by Django 3.1.4 on 2021-01-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210117_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentfactormodifier',
            old_name='Environment_Factor_Modifier',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='overpressuredemandcase',
            old_name='Over_pressure_demand_case',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='prddischargelocation',
            old_name='PRD_Discharge_Location',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='prdinspectioneffectiveness',
            old_name='PRD_Inspection_Effectiveness',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='protectedequipmentdemagestatus',
            old_name='Protected_Equipment_Demage_Status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='serviceseverity',
            old_name='Service_severity',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typeofprd',
            old_name='Type_of_PRD',
            new_name='name',
        ),
    ]
