# Generated by Django 3.1.1 on 2020-09-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_generalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrdInspection_TestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_Inspection_Test_Date', models.CharField(max_length=100)),
                ('PRD_Pop_Test_Results', models.CharField(choices=[('IPRD_10_first', 'Pass'), ('IPRD_10_second', 'Fail')], default='IPRD_10_first', max_length=15)),
            ],
            options={
                'ordering': ['PRD_Inspection_Test_Date'],
            },
        ),
        migrations.DeleteModel(
            name='PRD',
        ),
    ]
