# Generated by Django 3.1.4 on 2021-03-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_projectregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRegistration',
        ),
    ]
