# Generated by Django 3.1.1 on 2020-09-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20200922_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prdinspection_testhistory',
            options={'ordering': ['Fixed_Equipment_Protected_by_PRD']},
        ),
        migrations.RemoveField(
            model_name='prdinspection_testhistory',
            name='PRD_Inspection_Test_Date',
        ),
        migrations.RemoveField(
            model_name='prdinspection_testhistory',
            name='PRD_Pop_Test_Results',
        ),
        migrations.AddField(
            model_name='prdinspection_testhistory',
            name='Fixed_Equipment_Protected_by_PRD',
            field=models.CharField(choices=[('IPRD_18_first', 'V-100'), ('IPRD_18_second', 'V-101'), ('IPRD_18_third', 'Piping-2XXXX')], default='IPRD_18_first', max_length=20),
        ),
        migrations.AddField(
            model_name='prdinspection_testhistory',
            name='Protected_Equipment_Demage_Status',
            field=models.CharField(choices=[('IPRD_19_first', 'Minimal'), ('IPRD_19_second', 'Minor'), ('IPRD_19_third', 'Moderate'), ('IPRD_19_fourth', 'Severe')], default='IPRD_19_first', max_length=15),
        ),
    ]
