# Generated by Django 3.1.1 on 2020-09-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200922_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdinspection_testhistory',
            name='Maximum_Allow_able_Working_Pressure_of_Protected_Equipment',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prdinspection_testhistory',
            name='Operating_Pressure_of_the_Protected_Equipment',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prdinspection_testhistory',
            name='Protected_Equipment_Demage_Status',
            field=models.CharField(choices=[('IPRD_19_first', 'None'), ('IPRD_19_second', 'Minimal'), ('IPRD_19_third', 'Minor'), ('IPRD_19_fourth', 'Moderate'), ('IPRD_19_fifth', 'Severe')], default='IPRD_19_first', max_length=15),
        ),
    ]
