# Generated by Django 3.1.4 on 2021-03-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_projectregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmodels',
            name='PRD_Inspection_history',
        ),
        migrations.AddField(
            model_name='allmodels',
            name='PRD_Inspection_history',
            field=models.ManyToManyField(to='webapp.Prd_InspectionHistory'),
        ),
    ]
