# Generated by Django 3.1.1 on 2020-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20200922_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdinspection_testhistory',
            name='Multiple_PRDs_protecting_fixed_equipment',
            field=models.CharField(choices=[('IPRD_22_first', 'No'), ('IPRD_22_second', 'Yes')], default='IPRD_22_first', max_length=14),
        ),
    ]
