# Generated by Django 3.1.1 on 2020-09-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_prdinspection_testhistory_multiple_prds_protecting_fixed_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsequencesOfFailureInputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Multiple_PRDs_protecting_fixed_equipment', models.CharField(choices=[('IPRD_22_first', 'No'), ('IPRD_22_second', 'Yes')], default='IPRD_22_first', max_length=14)),
            ],
            options={
                'ordering': ['Multiple_PRDs_protecting_fixed_equipment'],
            },
        ),
    ]
