# Generated by Django 3.1.1 on 2020-09-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_consequencesoffailureinputdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='consequencesoffailureinputdata',
            name='Orifice_area_of_the_PRD',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
