# Generated by Django 3.1.1 on 2020-09-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_consequencesoffailureinputdata_orifice_area_of_the_prd'),
    ]

    operations = [
        migrations.AddField(
            model_name='consequencesoffailureinputdata',
            name='Total_installed_orifice_area_of_a_multiple_PDRs_installation',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
