# Generated by Django 3.1.1 on 2020-09-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_consequencesoffailureinputdata_total_installed_orifice_area_of_a_multiple_pdrs_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consequences0fFailureOfLeakage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rated_Capacity_of_PRD', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('PRD_Inlet_Size', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('Cost_of_the_fluid', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('Environmental_clean_up_costs_due_to_a_PRD_leakage', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
            ],
        ),
    ]
