# Generated by Django 3.1.1 on 2020-09-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_consequences0ffailureofleakage'),
    ]

    operations = [
        migrations.AddField(
            model_name='consequences0ffailureofleakage',
            name='Cost_of_shutdown_to_repair_PRD',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consequences0ffailureofleakage',
            name='Daily_production_margin_on_the_unit',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consequences0ffailureofleakage',
            name='Number_of_days_required_to_shutdown_a_unit_to_repair_a_leakage_or_stuck_open_PRD',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consequences0ffailureofleakage',
            name='PRD_leakage_can_be_tolered',
            field=models.CharField(choices=[('IPRD_30_first', 'No'), ('IPRD_30_second', 'Yes')], default='IPRD_30_first', max_length=14),
        ),
    ]
