# Generated by Django 3.1.1 on 2020-09-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20200922_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableOverpressureDemandCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Over_pressure_demand_case', models.CharField(choices=[('IPRD_16_first', 'Fire'), ('IPRD_16_second', 'Loss of cooling water utility'), ('IPRD_16_third', 'Electrical power supply failure'), ('IPRD_16_fourth', 'Blockage discharge with administrative controls in place'), ('IPRD_16_fifth', 'Blockage discharge without administrative controls'), ('IPRD_16_sixth', 'Control valve failure, initiating event is same direction as CV normal fail position (i.e. fail safe)'), ('IPRD_16_seventh', 'Control valve failure, initiating event is opposite direction as CV normal fail posiion (i.e. fail opposite)'), ('IPRD_16_eigth', 'Runaway chemical reaction'), ('IPRD_16_nineth', 'Heat exchanger tube rupture'), ('IPRD_16_tenth', 'Tower P/A or reflux pump failures')], default='IPRD_16_first', max_length=100)),
            ],
        ),
    ]
