# Generated by Django 3.1.1 on 2020-09-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_applicableoverpressuredemandcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicableoverpressuredemandcase',
            name='Overpressure_like_to_occur_associated_with_the_overpressure_demand_case',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='applicableoverpressuredemandcase',
            name='Over_pressure_demand_case',
            field=models.CharField(choices=[('IPRD_16_first', '1. Fire'), ('IPRD_16_second', '2. Loss of cooling water utility'), ('IPRD_16_third', '3. Electrical power supply failure'), ('IPRD_16_fourth', '4. Blockage discharge with administrative controls in place'), ('IPRD_16_fifth', '5. Blockage discharge without administrative controls'), ('IPRD_16_sixth', '6. Control valve failure, initiating event is same direction as CV normal fail position (i.e. fail safe)'), ('IPRD_16_seventh', '7. Control valve failure, initiating event is opposite direction as CV normal fail posiion (i.e. fail opposite)'), ('IPRD_16_eigth', '8. Runaway chemical reaction'), ('IPRD_16_nineth', '9. Heat exchanger tube rupture'), ('IPRD_16_tenth', '10. Tower P/A or reflux pump failures'), ('IPRD_16_eleventh', '11. Thermal relief with administrative controls in place'), ('IPRD_16_twelveth', '12. Thermal relief without administrative controls'), ('IPRD_16_thrirteenth', '13. Liquid overfilling with administrative controls in place'), ('IPRD_16_fourteenth', '14. Liquid overfilling without administrative controls')], default='IPRD_16_first', max_length=100),
        ),
    ]
