# Generated by Django 3.1.1 on 2020-09-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20200924_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicableoverpressuredemandcase',
            name='PRD_COF_to_open_associated_with_jth_overpressure_demand_case',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
