# Generated by Django 3.1.1 on 2020-09-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_applicableoverpressuredemandcase_prd_cof_to_open_associated_with_jth_overpressure_demand_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrdInspectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_inspection_test_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='Installation_of_PRD',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
