# Generated by Django 3.1.1 on 2020-09-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20200924_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='Installation_of_PRD',
        ),
    ]
