# Generated by Django 3.1.1 on 2020-09-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_generalinformation_installation_of_prd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prdinspectionhistory',
            name='PRD_inspection_test_date',
        ),
        migrations.AddField(
            model_name='prdinspectionhistory',
            name='PRD_Inspection_Effectiveness',
            field=models.CharField(choices=[('IPRD_13_first', 'A-Highly Effective'), ('IPRD_13_second', 'B-Usually Effective'), ('IPRD_13_first', 'C-Faily Effective'), ('IPRD_13_fourth', 'D-Ineffective')], default='IPRD_13_first', max_length=30),
        ),
        migrations.AddField(
            model_name='prdinspectionhistory',
            name='PRD_Leakage_results',
            field=models.CharField(choices=[('IPRD_12_first', 'Leak'), ('IPRD_12_second', 'No Leak')], default='IPRD_12_first', max_length=15),
        ),
        migrations.AddField(
            model_name='prdinspectionhistory',
            name='PRD_pop_test_results',
            field=models.CharField(choices=[('IPRD_11_first', 'Pass'), ('IPRD_11_second', 'Fail')], default='IPRD_11_first', max_length=15),
        ),
    ]
