# Generated by Django 3.1.1 on 2020-09-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20200924_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicableoverpressuredemandcase',
            old_name='Overpressure_like_to_occur_associated_with_the_overpressure_demand_case',
            new_name='Overpressure_associated_with_the_overpressure',
        ),
        migrations.RenameField(
            model_name='applicableoverpressuredemandcase',
            old_name='PRD_COF_to_open_associated_with_jth_overpressure_demand_case',
            new_name='PRD_COF_to_open_associated_with_jth_overpressure',
        ),
        migrations.RenameField(
            model_name='consequences0ffailureofleakage',
            old_name='Number_of_days_required_to_shutdown_a_unit_to_repair_a_leakage_or_stuck_open_PRD',
            new_name='Days_required_to_shutdown_a_unit_to_repair_a_leakage',
        ),
    ]
