# Generated by Django 3.1.1 on 2020-09-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20200924_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prd_InspectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_pop_test_results', models.CharField(choices=[('IPRD_11_first', 'Pass'), ('IPRD_11_second', 'Fail')], default='IPRD_11_first', max_length=15)),
                ('PRD_Leakage_results', models.CharField(choices=[('IPRD_12_first', 'Leak'), ('IPRD_12_second', 'No Leak')], default='IPRD_12_first', max_length=15)),
                ('PRD_Inspection_Effectiveness', models.CharField(choices=[('IPRD_13_first', 'A-Highly Effective'), ('IPRD_13_second', 'B-Usually Effective'), ('IPRD_13_first', 'C-Faily Effective'), ('IPRD_13_fourth', 'D-Ineffective')], default='IPRD_13_first', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='PrdInspectionHistory',
        ),
    ]
