# Generated by Django 3.1.1 on 2020-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_auto_20200924_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd_inspectionhistory',
            name='PRD_Overhauled_during_the_inspection',
            field=models.CharField(choices=[('IPRD_14_first', 'Yes'), ('IPRD_14_second', 'No')], default='IPRD_14_first', max_length=14),
        ),
        migrations.AddField(
            model_name='prd_inspectionhistory',
            name='PRD_replace_with_new_PRD_in_lieu_of_overhaul',
            field=models.CharField(choices=[('IPRD_15_first', 'Yes'), ('IPRD_15_second', 'No')], default='IPRD_15_first', max_length=14),
        ),
    ]
