# Generated by Django 3.1.1 on 2020-10-09 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20201009_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='Installation_of_PRD',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
