# Generated by Django 3.1.1 on 2020-10-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20201009_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prdinspection_testhistory',
            name='Multiple_PRDs_protecting_fixed_equipment',
        ),
    ]
