# Generated by Django 3.1.1 on 2020-10-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_remove_prdinspection_testhistory_multiple_prds_protecting_fixed_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicableoverpressuredemandcase',
            name='Over_pressure_demand_case',
            field=models.CharField(choices=[('fire', '1. Fire'), ('loss_of_cooling_water', '2. Loss of cooling water utility'), ('electrical_power_supply_failure', '3. Electrical power supply failure'), ('blockage_discharge_with_admin_controls', '4. Blockage discharge with administrative controls in place'), ('blockage_discharge_without_admin_controls', '5. Blockage discharge without administrative controls'), ('control_valve_failure_initiating_event_is_same_direction_as_CV', '6. Control valve failure, initiating event is same direction as CV normal fail position (i.e. fail safe)'), ('control_valve_failure_initiating_event_is_opposite_direction_as_CV', '7. Control valve failure, initiating event is opposite direction as CV normal fail posiion (i.e. fail opposite)'), ('runaway_chemical_reaction', '8. Runaway chemical reaction'), ('heat_exchanger_tube_rupture', '9. Heat exchanger tube rupture'), ('tower_P/A_or_reflux_pump_failures', '10. Tower P/A or reflux pump failures'), ('thermal_relief_with_admini_controls', '11. Thermal relief with administrative controls in place'), ('thermal_relief_without_admin_controls', '12. Thermal relief without administrative controls'), ('liquid_overfilling_with_admin_controls', '13. Liquid overfilling with administrative controls in place'), ('liquid_overfilling_without_admin_controls', '14. Liquid overfilling without administrative controls')], default='fire', max_length=100),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='PRD_leakage_can_be_tolered',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=14),
        ),
        migrations.AlterField(
            model_name='consequencesoffailureinputdata',
            name='Multiple_PRDs_protecting_fixed_equipment',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=14),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='Environment_Factor_Modifier',
            field=models.CharField(choices=[('99.33 °C < T < 260 °C', 'Operating temperatures 99.33 °C < T < 260 °C'), ('> 260 °C', 'Operating temperature > 260 °C'), ('>_90%_spring-loaded_or_>_95%_pilot-operated', 'Operating ratio > 90%\\ for spring-loaded PRVs or > 95% for pilot operated'), ('installed_piping_vibration', 'Installed piping vibration'), ('pulsating_or_cyclical_service', 'Pulsating or cyclical service such as downstream of positive displacement rotating equipment'), ('history_of_excessive_actuation', 'History of excessive actuation in service (greater than 5 times per year'), ('history_of_chatter', 'History of chatter')], default='99.33 °C < T < 260 °C', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='PRD_Containing_Soft_Seats',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=15),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='PRD_Discharge_Location',
            field=models.CharField(choices=[('atmosphere', 'Atmosphere'), ('flare', 'Flare'), ('closed_process', 'Closed Process')], default='atmosphere', max_length=25),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='Rupture_disk_is_installed_upstream_of_PRD',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=13),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='Service_severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=15),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='Type_of_PRD',
            field=models.CharField(choices=[('convention_spring_loaded', 'Convention Spring-Loaded'), ('balanced_bellows', 'Balanced Bellows'), ('pilot_operated', 'Pilot Operated'), ('prv_with_rupture_disk', 'PRV with Rupture Disk'), ('Rupture_disk_only', 'Rupture Disk Only')], default='convention_spring_loaded', max_length=25),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Inspection_Effectiveness',
            field=models.CharField(choices=[('highly_effective', 'A-Highly Effective'), ('usually_effective', 'B-Usually Effective'), ('faily_effective', 'C-Faily Effective'), ('ineffective', 'D-Ineffective')], default='highly_effective', max_length=30),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Leakage_results',
            field=models.CharField(choices=[('leak', 'Leak'), ('no_leak', 'No Leak')], default='pass', max_length=15),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Overhauled_during_the_inspection',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=14),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_pop_test_results',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='fire', max_length=15),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_replace_with_new_PRD_in_lieu_of_overhaul',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=14),
        ),
        migrations.AlterField(
            model_name='prdinspection_testhistory',
            name='Fixed_Equipment_Protected_by_PRD',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='prdinspection_testhistory',
            name='Protected_Equipment_Demage_Status',
            field=models.CharField(choices=[('none', 'None'), ('minimal', 'Minimal'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=15),
        ),
    ]
