# Generated by Django 3.1.1 on 2020-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_auto_20201015_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequencesoffailureinputdata',
            name='Multiple_PRDs_protecting_fixed_equipment',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='yes', max_length=14),
        ),
    ]
