# Generated by Django 3.1.1 on 2020-10-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_auto_20201015_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequencesoffailureinputdata',
            name='Multiple_PRDs_protecting_fixed_equipment',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=14),
        ),
    ]
