# Generated by Django 3.1.1 on 2020-10-16 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20201015_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd_inspectionhistory',
            name='RBI_inspection_test_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
