# Generated by Django 3.1.1 on 2020-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_prd_inspectionhistory_rbi_inspection_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicableoverpressuredemandcase',
            name='Overpressure_associated_with_the_overpressure',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='applicableoverpressuredemandcase',
            name='PRD_COF_to_open_associated_with_jth_overpressure',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='Cost_of_shutdown_to_repair_PRD',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='Cost_of_the_fluid',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='Daily_production_margin_on_the_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='Days_required_to_shutdown_a_unit_to_repair_a_leakage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='Environmental_clean_up_costs_due_to_a_PRD_leakage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='PRD_Inlet_Size',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='Rated_Capacity_of_PRD',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequencesoffailureinputdata',
            name='Orifice_area_of_the_PRD',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consequencesoffailureinputdata',
            name='Total_installed_orifice_area_of_a_multiple_PDRs_installation',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='PRD_set',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prdinspection_testhistory',
            name='Maximum_Allow_able_Working_Pressure_of_Protected_Equipment',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prdinspection_testhistory',
            name='Operating_Pressure_of_the_Protected_Equipment',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
