# Generated by Django 3.1.1 on 2020-10-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_auto_20201017_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='PRD_identification_number',
            field=models.CharField(default='ABC', max_length=10),
        ),
    ]
