# Generated by Django 3.1.1 on 2020-10-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_auto_20201023_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Inspection_Effectiveness',
            field=models.CharField(choices=[('none', 'None'), ('highly_effective', 'A-Highly Effective'), ('usually_effective', 'B-Usually Effective'), ('faily_effective', 'C-Faily Effective'), ('ineffective', 'D-Ineffective')], default='highly_effective', max_length=30),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_pop_test_results',
            field=models.CharField(choices=[('none', 'None'), ('pass', 'Pass'), ('fail', 'Fail')], default='fire', max_length=15),
        ),
    ]
