# Generated by Django 3.1.1 on 2020-10-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_auto_20201023_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='RBI_inspection_test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
