# Generated by Django 3.1.1 on 2020-10-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_auto_20201023_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Leakage_results',
            field=models.CharField(choices=[('none', 'None'), ('leak', 'Leak'), ('no_leak', 'No Leak')], default='pass', max_length=15),
        ),
    ]
