# Generated by Django 3.1.1 on 2020-10-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_auto_20201023_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='Type_of_PRD',
            field=models.CharField(choices=[('convention_spring_loaded', 'Convention Spring-Loaded'), ('balanced_bellows', 'Balanced Bellows'), ('pilot_operated', 'Pilot Operated'), ('Rupture_disk_only', 'Rupture Disk Only')], default='convention_spring_loaded', max_length=25),
        ),
    ]
