# Generated by Django 3.1.1 on 2020-10-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_auto_20201027_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Inspection_Effectiveness',
            field=models.CharField(choices=[('none', 'None'), ('highly_effective', 'Highly Effective'), ('usually_effective', 'Usually Effective'), ('faily_effective', 'Faily Effective'), ('ineffective', 'Ineffective')], default='highly_effective', max_length=30),
        ),
    ]
