# Generated by Django 3.1.1 on 2020-11-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_auto_20201030_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='PRD_Inspection_Effectiveness',
            field=models.CharField(choices=[('none', 'None'), ('highly_effective', 'Highly Effective'), ('usually_effective', 'Usually Effective'), ('faily_effective', 'Faily Effective'), ('highly_effective', 'Highly Effective')], default='highly_effective', max_length=30),
        ),
    ]
