# Generated by Django 3.1.1 on 2020-11-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_auto_20201109_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdinspection_testhistory',
            name='management_system_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
