# Generated by Django 3.1.1 on 2020-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_prdinspection_testhistory_management_system_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequences0ffailureofleakage',
            name='Days_required_to_shutdown_a_unit_to_repair_a_leakage',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
