# Generated by Django 3.1.1 on 2020-11-28 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0053_auto_20201127_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='Installation_of_PRD',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='RBI_assessment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='prd_inspectionhistory',
            name='RBI_inspection_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
