# Generated by Django 3.1.1 on 2020-12-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_typeofprd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSeverity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=15)),
            ],
        ),
    ]
