# Generated by Django 3.1.1 on 2020-12-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0056_serviceseverity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDDischargeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_Discharge_Location', models.CharField(choices=[('atmosphere', 'Atmosphere'), ('flare', 'Flare'), ('closed_process', 'Closed Process')], default='atmosphere', max_length=25)),
            ],
        ),
    ]
