# Generated by Django 3.1.1 on 2020-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0057_prddischargelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentFactorModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Environment_Factor_Modifier', models.CharField(choices=[('99.33 °C < T < 260 °C', 'Operating temperatures 99.33 °C < T < 260 °C'), ('> 260 °C', 'Operating temperature > 260 °C'), ('>_90%_spring-loaded_or_>_95%_pilot-operated', 'Operating ratio > 90%\\ for spring-loaded PRVs or > 95% for pilot operated'), ('installed_piping_vibration', 'Installed piping vibration'), ('pulsating_or_cyclical_service', 'Pulsating or cyclical service such as downstream of positive displacement rotating equipment'), ('history_of_excessive_actuation', 'History of excessive actuation in service (greater than 5 times per year'), ('history_of_chatter', 'History of chatter')], default='99.33 °C < T < 260 °C', max_length=100)),
            ],
        ),
    ]
