# Generated by Django 3.1.1 on 2020-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0058_environmentfactormodifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedEquipmentDemageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protected_Equipment_Demage_Status', models.CharField(choices=[('none', 'None'), ('minimal', 'Minimal'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=15)),
            ],
        ),
    ]
