# Generated by Django 3.1.1 on 2020-12-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0060_prdinspectioneffectiveness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PRDInspectionEffectiveness',
        ),
    ]
