# Generated by Django 3.1.1 on 2020-12-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0061_delete_prdinspectioneffectiveness'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDInspectionEffectiveness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_Inspection_Effectiveness', models.CharField(choices=[('none', 'None'), ('highly_effective', 'Highly Effective'), ('usually_effective', 'Usually Effective'), ('faily_effective', 'Faily Effective'), ('highly_ineffective', 'Ineffective')], default='highly_effective', max_length=30)),
            ],
        ),
    ]
