# Generated by Django 3.1.1 on 2020-12-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_overpressuredemandcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Environment_Factor_Modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.environmentfactormodifier')),
                ('PRD_Discharge_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.prddischargelocation')),
                ('Service_severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.serviceseverity')),
                ('Type_of_PRD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.typeofprd')),
            ],
        ),
    ]
